### ISSUE TITLE
KeyError: 'fc7_conv'

### ISSUE THREAD

**Issue by albertyou2** [jinfagang/kitti-ssd#3]
hi @jinfagang  

when I run 'python train_ssd_kitti.py', I got this error :

Traceback (most recent call last):
  File "train_ssd_kitti.py", line 455, in <module>
    prior_variance=prior_variance, kernel_size=3, pad=1, lr_mult=lr_mult)
  File "/home/sojoyoo/caffe_ssd/python/caffe/model_libs.py", line 870, in CreateMultiBoxHead
    num_output=num_loc_output, kernel_size=kernel_size, pad=pad, stride=1, **bn_param)
  File "/home/sojoyoo/caffe_ssd/python/caffe/model_libs.py", line 97, in ConvBNLayer
    net[conv_name] = L.Convolution(net[from_layer], num_output=num_output,
  File "/home/sojoyoo/caffe_ssd/python/caffe/net_spec.py", line 188, in __getitem__
    return self.__getattr__(item)
  File "/home/sojoyoo/caffe_ssd/python/caffe/net_spec.py", line 182, in __getattr__
    return self.tops[name]
KeyError: 'fc7_conv'

Have you met this before?

**Comment by wenchima** [comment]
hi @albertyou2

Have you solved your problem? I changed the fc7_conv into fc7 and it worked well. But my problem is that my training loss is always be zero. Have you kept doing on this?

**Comment by albertyou2** [comment]
@wenchima 
No  , I didn't solve this.
 I 'm now switch to caffe_ssd .

**Comment by nattari** [comment]
Facing the same issue. Anyone solved it yet?

**Comment by ss32** [comment]
~~Same error, no luck~~

Looking at https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_pascal.py and comparing, they use `fc7` instead of `fc7_conv`.  Make the change and the script will run without error
